### ISSUE TITLE
Problem with VLFEAT

### ISSUE THREAD

**Issue by tulikaiam** [MartinHjelm/fishercaffe#3]
I tried using the cmake command and I'm getting this error.
I have installed vlfeat using matlab

You have called ADD_LIBRARY for library vlfeat without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:

**Comment by MartinHjelm** [comment]
Hi. In the outback far between a good internet connection. The vlfeat library needs to be in a subdirectory in the same directory if I remember it correctly. Also what I haven't updated in the code is that the vectors from the caffe needs to be l2 normalized to unit length. Can update this later next week.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
